HPIT.MVC/Controllers/NewsController.cs
using HPIT.MVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HPIT.MVC.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index(string year,string month,string day,int id)
        {
            //year = Request.QueryString["year"];
            //month = Request.QueryString["month"];
            //day = Request.QueryString["day"];
            //id = Convert.ToInt32(Request.QueryString["id"]);

            //直接通过Action定义的参数来获取http请求的数据，更方便快捷
            string str = $"{year}-{month}-{day}-{id}";

            //return Redirect("/Home/Index");//跳转URL
            //return RedirectToAction("Demo");//跳转Action
            //return RedirectToRoute("Default", new { controller = "Home", action = "Index"});//跳转路由

            var obj = new { Year = year, Month = month, Day = day, Id = id };

            //return Json(obj,JsonRequestBehavior.AllowGet); //返回json格式数据
            return View();
        }

        public ActionResult Demo()
        {
            ViewData["Data1"] = "我是ViewData数据";
            ViewBag.Data2 = "我是ViewBag数据";

            ViewBag.MyData = "物联5班到此一游~~";

            var model = new UserViewModel()
            {
                Address = "河南郑州",
                Age = 18,
                Name = "何老师"
            };
            ViewBag.UserInfo = model;

            return View();
        }

        public ActionResult Demo2()
        {
            var model = new UserViewModel()
            {
                Address = "河南郑州",
                Age = 18,
                Name = "何老师"
            };

            return View(model);
        }

        public ActionResult Demo3()
        {
            var model = new UserViewModel()
            {
                Address = "河南郑州",
                Age = 18,
                Name = "何老师"
            };

            return View(model);
        }

        //默认Get请求
        public ActionResult Register()
        {
            return View();
        }


        //指定Post请求
        [HttpPost]
        public ActionResult Register(UserViewModel model)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "眼睛睁大一点，再填一遍~");
                return View(model);
            }
            //把数据写入到数据库中，返回消息提示，代码略。
            return View();
        }
        
    }
}

HPIT.MVC/Views/News/Demo.cshtml
@{
    ViewBag.Title = "Demo";
}

<h2>Demo</h2>
<p>小样，我是Demo视图，啦啦啦啦啦啦啦啦啦~</p>
<p>@ViewData["Data1"]</p>
<p>@ViewBag.Data1</p>

<div>
    @ViewBag.MyData
</div>
@{
    var userInfo = ViewBag.UserInfo as HPIT.MVC.Models.UserViewModel;
    <p>@userInfo.Name</p>
    <p>@userInfo.Age</p>
    <p>@userInfo.Address</p>

}

HPIT.MVC/Views/News/Demo2.cshtml
@model HPIT.MVC.Models.UserViewModel

@{
    ViewBag.Title = "Demo2";
}

<h2>Demo2</h2>

<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>

    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HPIT.MVC/Views/News/Demo3.cshtml
@using HPIT.MVC.Models

@model UserViewModel


@{
    ViewBag.Title = "Demo3";
}

<h2>Demo3</h2>

<div>
    <h4>UserViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HPIT.MVC/Views/News/Hello.cshtml
@model HPIT.MVC.Models.Student

@{
    ViewBag.Title = "Hello";
}

<h2>Hello</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Student</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Mobile, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClassId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ClassId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

HPIT.MVC/Views/News/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>我是一个新视图，哈哈哈哈哈哈哈~</p>
@for (int i = 0; i < 5; i++)
{
    <p>我是Razor，你好啊，哈哈哈哈哈哈哈~</p>
}

HPIT.MVC/Views/News/Register.cshtml
@model HPIT.MVC.Models.UserViewModel

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm("Register","News",FormMethod.Post)) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UserViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>